language: cpp

# ubuntu 14.04 version
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
    - os: osx
      osx_image: xcode5
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        
    - os: osx
      osx_image: xcode6
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        
    - os: osx
      osx_image: xcode7
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        
        
before_script:
  - eval "${MATRIX_EVAL}"
  - $CXX --version
  
script:
  - mkdir build && cd ./build
  - cmake ..
  - make
  - ctest --extra-verbose
  
branches:
  only:
  - master
  
notifications:
  email: false
